version: '3.8'

services:
  pg_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_MAIN_DB}
    ports:
      - '${PG_PORT_HOST}:${PG_PORT_CONTAINER}'
    volumes:
      - pg_db:/var/lib/postgresql/data

volumes:
  pg_db:
    driver: local
