version: '3.8'

services:
  pg_db:
    image: postgres:15.4-alpine
    container_name: BB-pg
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_MAIN_DB}
    ports:
      - '${PG_PORT_HOST}:${PG_PORT_CONTAINER}'
    volumes:
      - pg_db:/var/lib/postgresql/data

  web:
    container_name: BB
    build: .
    command: sh -c "python src/app.py"
    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'
    volumes:
      - .:/app
    depends_on:
      - pg_db

volumes:
  pg_db:
    driver: local